default:
		g++-12 -I /usr/local/Cellar/boost/1.80.0/include/ -o main main.cpp
		./main
		rm main
ll:
		g++-12 -I /usr/local/Cellar/boost/1.80.0/include/ -o logless logless.cpp
		./logless
		rm logless
